### ISSUE TITLE
Typo in Readme

### ISSUE THREAD

**Issue by narnat** [arthurdamm/twodoor#135]
Hello, TwoDoor community!
I've found a typo:

> Twodoor is an adaptive virtual flashcard tutor written in JQuery, HTML5 & CSS3 & currently deployed as a ~wep~ web application at: https://holbie.app/

I hope it can be fixed soon!
Thank you!

**Comment by arthurdamm** [comment]
Issue fixed, and updated URL for current as holbie.app domain was given up.
